import { afterAll, beforeAll, describe, expect, it, setSystemTime } from "bun:test";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Menu } from "@grammyjs/menu";
import type { Context, InlineKeyboard } from "grammy";
import { analyticsKeyboard } from "../src/bot/analytics-screen.js";
import { openIntake } from "../src/bot/intake.js";
import { buildMainMenu } from "../src/bot/navigation.js";
import { draftPreview } from "../src/bot/preview.js";
import { postProgress } from "../src/bot/progress.js";
import { attentionView, queueView } from "../src/bot/queue.js";
import { candidateView, radarHomeView } from "../src/bot/radar-screen.js";
import { buildSettingsMenu } from "../src/bot/settings/index.js";
import {
  BACKUP_MENU_ID,
  CHANNEL_CONNECT_MENU_ID,
  CHANNEL_DISABLE_MENU_ID,
  CHANNEL_MENU_ID,
  CHANNELS_MENU_ID,
  DEFAULT_TARGETS_MENU_ID,
  MILESTONES_MENU_ID,
  NOTIFICATION_SETTINGS_MENU_ID,
  NOTIFICATIONS_MENU_ID,
  PUBLISHING_MENU_ID,
  RADAR_MENU_ID,
  SYSTEM_MENU_ID,
} from "../src/bot/settings/shared.js";
import { showStreamScreen } from "../src/bot/stream-screen.js";
import { createDraftFromMessage } from "../src/content/drafts.js";
import type { UnsafeBackendDb } from "../src/db/client.js";
import { videoPreview } from "../src/interfaces/telegram/video-preview.js";
import { publishDraftToQueue } from "../src/publishing/publication-workflow.js";
import { replaceVideoTargets } from "../src/publishing/video-service.js";
import { videoService } from "../src/studio/services/videos.js";
import { registerTestChannels, TEXT_TEST_CHANNELS, VIDEO_TEST_CHANNELS } from "./helpers/channels.js";
import { openBackendDb } from "./helpers/open-db.js";
import { loadTestConfig } from "./helpers/studio-config.js";
import { createTestVideoDraft } from "./helpers/video.js";

/** Every screen the bot can put on the operator's phone, written down.
 *
 * Reviewing a keyboard change used to mean opening the bot and walking to the
 * screen. Here the whole surface is one file: a moved button, a lost way back
 * or a control that quietly appeared shows up as a line in the diff of this
 * snapshot, next to the change that caused it.
 *
 * Refresh it with `UPDATE_SCREENS=1 bun test apps/backend/tests/botScreens.test.ts`
 * and read what moved before committing. */
const SNAPSHOT = join(import.meta.dir, "screens/bot-screens.txt");

const config = loadTestConfig({ CONTROLLER_ADMIN_IDS: "42", TIMEZONE: "UTC" });
/** A fixed clock, so "today" in a queue row is the same word every day and the
 * snapshot only moves when a screen does. */
const NOW = new Date("2026-03-05T09:00:00.000Z");
const fakeCtx = { from: { id: 42 }, chat: { id: 42 } } as unknown as Context;

function keyboardRows(keyboard: InlineKeyboard): string[] {
  // The label and where it leads: a button that keeps its text but changes its
  // destination is exactly the kind of move worth seeing in a diff.
  return keyboard.inline_keyboard.map((row) =>
    row.map((button) => `[${button.text} → ${"callback_data" in button ? button.callback_data : "url"}]`).join(" "),
  );
}

async function menuRows(menu: Menu<Context>): Promise<string[]> {
  const rows: Array<Array<{ text: string }>> = await (
    menu as unknown as { render: (ctx: Context) => Promise<Array<Array<{ text: string }>>> }
  ).render(fakeCtx);
  return rows.map((row) => row.map((button) => `[${button.text}]`).join(" "));
}

function section(title: string, rows: string[]): string {
  return [`## ${title}`, ...(rows.length ? rows : ["(no buttons)"]), ""].join("\n");
}

function seedStudio(): UnsafeBackendDb {
  const backendDb = openBackendDb(":memory:");
  registerTestChannels(backendDb, [...TEXT_TEST_CHANNELS, ...VIDEO_TEST_CHANNELS]);
  return backendDb;
}

async function renderScreens(backendDb: UnsafeBackendDb): Promise<string> {
  const parts: string[] = ["# Bot screens", "", "Generated by botScreens.test.ts. Every inline keyboard the bot can show, by screen.", ""];
  const settingsMenu = buildSettingsMenu(config, backendDb);
  const mainMenu = buildMainMenu(config, backendDb, settingsMenu);
  parts.push(section("Main menu", await menuRows(mainMenu)));
  for (const [title, id] of [
    ["Settings", undefined],
    ["Settings · Publishing", PUBLISHING_MENU_ID],
    ["Settings · Publishing · Channels", CHANNELS_MENU_ID],
    ["Settings · Publishing · Channels · One channel", CHANNEL_MENU_ID],
    ["Settings · Publishing · Channels · One channel · Disable", CHANNEL_DISABLE_MENU_ID],
    ["Settings · Publishing · Channels · Connect", CHANNEL_CONNECT_MENU_ID],
    ["Settings · Publishing · Default targets", DEFAULT_TARGETS_MENU_ID],
    ["Settings · Notifications", NOTIFICATIONS_MENU_ID],
    ["Settings · Notifications · Publication notices", NOTIFICATION_SETTINGS_MENU_ID],
    ["Settings · Notifications · Radar", RADAR_MENU_ID],
    ["Settings · Notifications · Achievements", MILESTONES_MENU_ID],
    ["Settings · System", SYSTEM_MENU_ID],
    ["Settings · System · Backup", BACKUP_MENU_ID],
  ] as const) {
    parts.push(section(title, await menuRows(id ? settingsMenu.at(id) : settingsMenu)));
  }

  const draftId = createDraftFromMessage(backendDb, 42, { text: "Черновик", textEn: "Draft", entities: [], media: [] });
  for (const view of ["overview", "platforms", "schedule", "schedule_ru", "confirm_publish", "confirm_delete"] as const) {
    parts.push(section(`Post card · ${view}`, keyboardRows(draftPreview(backendDb, draftId, config, "en", view).keyboard)));
  }

  const scheduledId = createDraftFromMessage(backendDb, 42, { text: "Запланирован", textEn: "Scheduled", entities: [], media: [] });
  const at = new Date(NOW.getTime() + 3 * 60 * 60_000);
  publishDraftToQueue(backendDb, scheduledId, { mode: "scheduled", ruAt: at, enAt: at });
  parts.push(section("Post card · scheduled", keyboardRows(draftPreview(backendDb, scheduledId, config, "en").keyboard)));
  parts.push(section("Publication progress", keyboardRows(postProgress(backendDb, scheduledId).keyboard)));
  parts.push(section("Publication progress · details", keyboardRows(postProgress(backendDb, scheduledId, true).keyboard)));

  const videoId = createTestVideoDraft(backendDb, 42, "clip.mp4", 24);
  replaceVideoTargets(backendDb, videoId, ["youtube_shorts", "instagram_reels"]);
  const videos = videoService(backendDb, config);
  for (const view of ["overview", "confirm_now", "confirm_cancel"] as const) {
    const preview = videoPreview(videos.preview(42, videoId), config, "en", { view });
    parts.push(section(`Video card · ${view}`, keyboardRows(preview.keyboard)));
  }

  for (const view of ["overview", "posts", "video"] as const)
    parts.push(section(`Analytics · ${view}`, keyboardRows(analyticsKeyboard("en", view, 7))));
  parts.push(section("Radar", keyboardRows(radarHomeView(backendDb, config, 42).keyboard)));
  parts.push(
    section(
      "Radar · one finding",
      keyboardRows(
        candidateView(
          {
            id: 7,
            producer: "news",
            title: "A finding",
            summary: "What happened.",
            reason: "Why this Studio should cover it.",
            url: "https://example.com/a",
            sourceHost: "example.com",
            relatedPostIds: [],
            entitySlugs: [],
            score: 60,
            status: "new",
            createdAt: "2026-03-05T08:00:00.000Z",
          },
          "en",
        ).keyboard,
      ),
    ),
  );
  parts.push(section("Work queue", keyboardRows(queueView(backendDb, config, 42).keyboard)));
  parts.push(section("Work queue · needs attention", keyboardRows(attentionView(backendDb, config, 42).keyboard)));

  parts.push(...(await intakeScreens(backendDb)));
  return parts.join("\n");
}

/** The stream screen renders what YouTube is doing right now, so it is the one
 * screen the surface cannot record without answering for YouTube. Both states
 * are recorded: a stream on the air carries a chat, and one that has not
 * started has no chat to say anything in. */
async function streamScreens(
  backendDb: UnsafeBackendDb,
  ctx: Context,
  sent: Array<{ text: string; keyboard?: InlineKeyboard }>,
): Promise<string[]> {
  registerTestChannels(backendDb, ["youtube_ru"]);
  const config = loadTestConfig({
    YOUTUBE_RU_CLIENT_ID: "client",
    YOUTUBE_RU_CLIENT_SECRET: "secret",
    YOUTUBE_RU_REFRESH_TOKEN: "refresh",
  });
  const screens: string[] = [];
  const original = globalThis.fetch;
  try {
    for (const [name, status, snippet] of [
      ["on the air", "live", { title: "Стримс", description: "", liveChatId: "chat-1" }],
      ["starting", "ready", { title: "Стримс", description: "" }],
      ["nothing running", null, null],
    ] as const) {
      globalThis.fetch = Object.assign(
        async (url: string | URL) =>
          String(url).includes("oauth2")
            ? Response.json({ access_token: "token" })
            : Response.json({ items: status ? [{ id: "bc-1", snippet, status: { lifeCycleStatus: status } }] : [] }),
        { preconnect: original.preconnect },
      ) as typeof fetch;
      await showStreamScreen(ctx, backendDb, config);
      const screen = sent.at(-1);
      screens.push(section(`Stream · ${name}`, screen?.keyboard ? keyboardRows(screen.keyboard) : []));
    }
  } finally {
    globalThis.fetch = original;
  }
  return screens;
}

async function intakeScreens(backendDb: UnsafeBackendDb): Promise<string[]> {
  const screens: string[] = [];
  const sent: Array<{ text: string; keyboard?: InlineKeyboard }> = [];
  const ctx = {
    from: { id: 42 },
    chat: { id: 42 },
    reply: async (text: string, options?: { reply_markup?: InlineKeyboard }) => {
      sent.push({ text, ...(options?.reply_markup ? { keyboard: options.reply_markup } : {}) });
      return { message_id: sent.length };
    },
  } as unknown as Context;
  await openIntake(ctx, backendDb, "text");
  const prompt = sent.at(-1);
  screens.push(section("Intake · prompt", prompt?.keyboard ? keyboardRows(prompt.keyboard) : []));
  screens.push(...(await streamScreens(backendDb, ctx, sent)));
  return screens;
}

describe("bot screens", () => {
  beforeAll(() => setSystemTime(NOW));
  afterAll(() => setSystemTime());

  it("matches the recorded surface", async () => {
    const backendDb = seedStudio();
    try {
      const rendered = `${await renderScreens(backendDb)}\n`;
      if (process.env.UPDATE_SCREENS) writeFileSync(SNAPSHOT, rendered);
      expect(rendered).toBe(readFileSync(SNAPSHOT, "utf8"));
    } finally {
      backendDb.close();
    }
  });
});
